name: PR Validation

on:
  pull_request:
    paths:
      - '**/*.usd*'

jobs:
  run-usdchecker:
    name: Run usdchecker
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v37
      with:
        files: |
          **/*.usd*
        files_ignore_from_source_file: .github/usdchecker-skiplist.txt

    - name: Install usd-core PyPI package
      run: pip install usd-core --user

    - name: Patch usd-core for USD issue 3055
      run: |
        mkdir -p /home/runner/.local/lib/python3.10/site-packages/pxr/pluginfo/usdHydra/resources/shaders
        mkdir -p /home/runner/.local/lib/python3.10/site-packages/pxr/pluginfo/usdHydra/resources
        mkdir -p /home/runner/.local/lib/python3.10/site-packages/pxr/pluginfo/usdHydra/shaders
        mkdir -p /home/runner/.local/lib/python3.10/site-packages/pxr/UsdHydra/shaders
        mkdir -p /home/runner/.local/lib/python3.10/site-packages/pxr/UsdHydra/resources/shaders
        cp .github/shaderDefs.usda /home/runner/.local/lib/python3.10/site-packages/pxr/pluginfo/usdHydra/resources/shaders
        cp .github/shaderDefs.usda /home/runner/.local/lib/python3.10/site-packages/pxr/pluginfo/usdHydra/resources
        cp .github/shaderDefs.usda /home/runner/.local/lib/python3.10/site-packages/pxr/pluginfo/usdHydra/shaders
        cp .github/shaderDefs.usda /home/runner/.local/lib/python3.10/site-packages/pxr/UsdHydra/shaders
        cp .github/shaderDefs.usda /home/runner/.local/lib/python3.10/site-packages/pxr/UsdHydra/resources/shaders

    - name: Test usdchecker
      run: python .github/usdchecker.py --help

    - name: Run usdchecker on changed USD files
      run: |
        set +e
        exit_code=0
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Checking $file"
            TF_DEBUG="PLUG*" python .github/usdchecker.py $file
            if ! $?; then
                exit_code=1;
            fi
        done
        exit $exit_code
